name: GoBuildRunTest

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: 
          cd Lab2\mainprog
          go build

    - name: Run
      run:
          cd Lab2\mainprog
          go run Main.go -f Text.md
          go run Main.go -f -o Text.md Res.html

    - name: Test
      run: 
          cd Lab2
          go test 
