name: GoBuildRunTest

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      working-directory: Lab2\mainprog\
      run: go build

    - name: Run1
      working-directory: Lab2\mainprog\
      run: go run Main.go -f Text.md

    - name: Run2
      working-directory: Lab2\mainprog\
      run: go run Main.go -f -o Text.md Res.html
      
    - name: Test
      working-directory: Lab2\
      run: go test
